<a href="https://colab.research.google.com/github/fred-lafleche/Exchange/blob/master/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
#imports
from sklearn import preprocessing
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
import numpy as np
import pandas as pd

In [3]:
input_file = "/content/drive/MyDrive/Colab Notebooks/online_shoppers_intention.csv"
#10 numerical and 8 categorical attributes, where revenue is class label
#12330 rows and 18 columns
data = pd.read_csv(input_file)
data.head()
#print(data["VisitorType"][1000]

Administrative  Administrative_Duration  ...  Weekend  Revenue
0               0                      0.0  ...    False    False
1               0                      0.0  ...    False    False
2               0                      0.0  ...    False    False
3               0                      0.0  ...    False    False
4               0                      0.0  ...     True    False

[5 rows x 18 columns]

In [ ]:
# Standardization, or mean removal and variance scaling

In [4]:
# Normalization
# Numerical data: Administrative	Administrative_Duration	Informational	Informational_Duration	ProductRelated	ProductRelated_Duration	BounceRates	ExitRates	PageValues	SpecialDay	
#data = preprocessing.normalize(data["Administrative","Administrative_Duration"])
#Scaled data has zero mean and unit variance
dataArray = data.values
numericData = dataArray[:,[0,1,2,3,4,5,6,7,8,9]]
scaler = preprocessing.StandardScaler().fit(numericData)
scalledNumericData = scaler.transform(numericData)
print(scalledNumericData.mean(axis=0))
print(scalledNumericData.std(axis=0))

[-2.99661170e-17  6.33898629e-17 -4.61017185e-18 -2.07457733e-17
  4.61017185e-17 -1.01423781e-16 -5.99322340e-17  3.22712029e-17
  1.06033952e-16 -5.53220622e-17]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [51]:
# One hot encoding
# Categorical data: Month	OperatingSystems	Browser	Region	TrafficType	VisitorType	Weekend	Revenue
# OperatingSystems	Browser	Region	TrafficType are already converted to numbers
categoricalData = dataArray[:,[10,15,16]]
categoricalLabel = dataArray[:,[17]]
encoder1 = preprocessing.OneHotEncoder()
encoder2 = preprocessing.OneHotEncoder()
encoder1.fit(categoricalData)
encoder2.fit(categoricalLabel)
categoricalData=encoder1.transform(categoricalData).toarray()
categoricalLabel = encoder2.transform(categoricalLabel).toarray()
print(categoricalData)
print(categoricalLabel)
print(encoder1.categories_)
print(encoder2.categories_)

[[0. 0. 1. ... 1. 1. 0.]
 [0. 0. 1. ... 1. 1. 0.]
 [0. 0. 1. ... 1. 1. 0.]
 ...
 [0. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[array(['Aug', 'Dec', 'Feb', 'Jul', 'June', 'Mar', 'May', 'Nov', 'Oct',
       'Sep'], dtype=object), array(['New_Visitor', 'Other', 'Returning_Visitor'], dtype=object), array([False, True], dtype=object)]
[array([False, True], dtype=object)]


In [49]:
#join data back together
#data=np.concatenate((scalledNumericData, categoricalData))
data = np.column_stack((scalledNumericData, categoricalData))
#add back columns 11 to 14 and 17
data = np.column_stack((data, dataArray[:,[11,12,13,14]]))
print(data[0],"\nAnswer: ",categoricalLabel[0])


[-0.6969929641233985 -0.4571914023726529 -0.39647790101721353
 -0.24493050612963665 -0.6910031807070663 -0.6243475187901789
 3.667188794132383 3.229315594758881 -0.31717784430961626
 -0.3088213656157659 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
 1.0 0.0 1 1 1 1] 
Answer:  [1. 0.]


In [52]:
#Features(30): Administrative	Administrative_Duration	Informational	Informational_Duration	ProductRelated	ProductRelated_Duration	BounceRates	ExitRates	PageValues	SpecialDay	Aug Dec Feb July June Mar May Nov Oct Sept New_Visitor other returning_visitor, false true	OperatingSystems	Browser	Region	TrafficTyp	Revenue
# Feature selection
#todo
#label does not need both values, so we'll only keep the value for true
label = categoricalLabel[:,[1]]
print(label)
print(data[1],"\nAnswer: ",label[1])


[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[-0.6969929641233985 -0.4571914023726529 -0.39647790101721353
 -0.24493050612963665 -0.66851798144781 -0.5909025573961064
 -0.45768299649364935 1.171472500128347 -0.31717784430961626
 -0.3088213656157659 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
 1.0 0.0 2 2 1 2] 
Answer:  [0.]


In [53]:
#Divide data, 70% for training, 30% for testing
#12330 rows * 0.7 = 8631
training_data=data[0:8631]
training_label=label[0:8631]

testing_data=data[8631:12330]
testing_label=label[8631:12330]

print("Total number of lines:", len(training_data)+len(testing_data))

Total number of lines: 12330


In [57]:
# single decision tree
SDT = tree.DecisionTreeClassifier()
SDT = SDT.fit(training_data,training_label)
SDT.predict(training_data)

array([0., 0., 0., ..., 0., 1., 0.])

In [ ]:
# random forest


In [61]:
# support vector machine (svm)
s_v_m = svm.SVC()
s_v_m = s_v_m.fit(training_data,training_label)
s_v_m.predict(testing_data)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
# k-nearest neighbor (k-NN)